### PR TITLE
fix: model not shared

### PR DESCRIPTION
**Pull request by matyasfodor**

### CODE REVIEW

**Review by kvikshaug — CHANGES_REQUESTED** [review]
This works well, but I think we should query the list of models from the model service. In the future that query may potentially return proprietary models the user has access to as well.

**Comment by matyasfodor** [comment]
@kvikshaug very good point. Could you please tell me which endpoint to query for the available models?

**Comment by kvikshaug** [comment]
This list shows which models have maps https://api.dd-decaf.eu/maps

**Comment by matyasfodor** [comment]
@kvikshaug fixed. Should work with https://github.com/DD-DeCaF/decaf-metabolica/pull/27

**Review by kvikshaug — APPROVED** [review]
Great 👍

**Pull request merged**
